# Generated by Django 5.2.1 on 2025-05-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Hostel', 'Hostel'), ('IT', 'IT'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
