# Generated by Django 5.2.1 on 2025-05-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_area_complaint_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='complaint',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='complaint',
            name='person_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='area',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('WATER', 'Water'), ('Hostel', 'Hostel'), ('Elctricity', 'Elctricity'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
